#!/usr/bin/env -S npx tsx
/**
 * Generates `server/modules/session/wordlist.generated.ts` from
 * `server/modules/session/wordlist.sv.txt`.
 *
 * Why a generated module instead of reading the .txt file at runtime: the app is built with
 * Vite/react-router for SSR, and a plain-text asset read via `node:fs` relative to
 * `import.meta.url` is not guaranteed to survive the SSR bundling step (the file may not be
 * copied next to the emitted bundle, or the bundler may rewrite `import.meta.url` in a way
 * that breaks a relative `fs.readFileSync`). Emitting a `.ts` module with the word array baked
 * in sidesteps all of that: it is just a regular ES module import, so it bundles exactly like
 * any other source file. Run via `pnpm build:wordlist` whenever `wordlist.sv.txt` changes; the
 * generated file is checked in like any other source file.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const srcPath = fileURLToPath(new URL("../server/modules/session/wordlist.sv.txt", import.meta.url));
const outPath = fileURLToPath(new URL("../server/modules/session/wordlist.generated.ts", import.meta.url));

const WORD_RE = /^[a-z]{3,8}$/;

function main() {
  const raw = readFileSync(srcPath, "utf8");
  const words = raw.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);

  if (words.length < 2048) {
    throw new Error(`wordlist too short: ${words.length} words, need >= 2048`);
  }
  const seen = new Set<string>();
  for (const word of words) {
    if (!WORD_RE.test(word)) {
      throw new Error(`invalid word in wordlist: ${JSON.stringify(word)}`);
    }
    if (seen.has(word)) {
      throw new Error(`duplicate word in wordlist: ${JSON.stringify(word)}`);
    }
    seen.add(word);
  }

  const body = words.map((w) => JSON.stringify(w)).join(",\n  ");
  const out = `// GENERATED FILE. Do not edit by hand.
// Generated by scripts/build-wordlist.ts from wordlist.sv.txt. Run \`pnpm build:wordlist\`
// after changing the source wordlist.

export const WORDLIST: readonly string[] = [
  ${body},
];
`;
  writeFileSync(outPath, out, "utf8");
  console.log(`Wrote ${words.length} words to ${outPath}`);
}

main();
